app = "enygma-app"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  NODE_ENV = "production"
  TMDB_API_KEY = "b9b334be32f57187296a06cfed4f2821"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443
